"""Professional email service with templates."""
import smtplib
from email.message import EmailMessage
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders
from typing import Optional
from datetime import datetime
from config import Config
from logger import app_logger

class EmailService:
    """Send professional emails with attachments."""
    
    @staticmethod
    def create_results_email_html(username: str, gene_count: int, 
                                   successful: int, organism: str) -> str:
        """Create HTML email template for results."""
        return f"""
        <!DOCTYPE html>
        <html>
        <head>
            <style>
                body {{
                    font-family: Arial, sans-serif;
                    line-height: 1.6;
                    color: #333;
                    max-width: 600px;
                    margin: 0 auto;
                    padding: 20px;
                }}
                .header {{
                    background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                    color: white;
                    padding: 30px;
                    text-align: center;
                    border-radius: 10px 10px 0 0;
                }}
                .content {{
                    background: #f9f9f9;
                    padding: 30px;
                    border: 1px solid #e0e0e0;
                }}
                .summary {{
                    background: white;
                    padding: 20px;
                    border-radius: 8px;
                    margin: 20px 0;
                    border-left: 4px solid #667eea;
                }}
                .stat {{
                    display: inline-block;
                    margin: 10px 20px 10px 0;
                }}
                .stat-label {{
                    font-size: 12px;
                    color: #666;
                    text-transform: uppercase;
                }}
                .stat-value {{
                    font-size: 24px;
                    font-weight: bold;
                    color: #667eea;
                }}
                .footer {{
                    text-align: center;
                    padding: 20px;
                    color: #666;
                    font-size: 12px;
                    border-top: 1px solid #e0e0e0;
                }}
                .button {{
                    display: inline-block;
                    padding: 12px 24px;
                    background: #667eea;
                    color: white;
                    text-decoration: none;
                    border-radius: 5px;
                    margin: 10px 0;
                }}
            </style>
        </head>
        <body>
            <div class="header">
                <h1>🧬 Gene Sequence Results Ready</h1>
            </div>
            <div class="content">
                <p>Hi {username},</p>
                <p>Your gene sequence extraction has been completed successfully!</p>
                
                <div class="summary">
                    <h3>📊 Summary</h3>
                    <div class="stat">
                        <div class="stat-label">Total Genes</div>
                        <div class="stat-value">{gene_count}</div>
                    </div>
                    <div class="stat">
                        <div class="stat-label">Successful</div>
                        <div class="stat-value">{successful}</div>
                    </div>
                    <div class="stat">
                        <div class="stat-label">Organism</div>
                        <div class="stat-value" style="font-size: 16px;">{organism}</div>
                    </div>
                </div>
                
                <p><strong>📎 Attachments included:</strong></p>
                <ul>
                    <li>ZIP file with all sequences</li>
                    <li>Metadata CSV with composition analysis</li>
                    <li>Metadata Excel workbook</li>
                </ul>
                
                <p>The sequences are in NCBI RefSeq format and include comprehensive metadata.</p>
            </div>
            <div class="footer">
                <p>Generated by Gene Extractor on {datetime.now().strftime('%B %d, %Y at %I:%M %p')}</p>
                <p style="color: #999; font-size: 11px;">This is an automated message. Please do not reply to this email.</p>
            </div>
        </body>
        </html>
        """
    
    @staticmethod
    def send_results_email(to_email: str, username: str, zip_bytes: bytes,
                          csv_bytes: Optional[bytes] = None, 
                          xlsx_bytes: Optional[bytes] = None,
                          gene_count: int = 0, successful: int = 0,
                          organism: str = "Unknown") -> tuple[bool, str]:
        """Send results email with attachments."""
        
        # Validate configuration
        sender = Config.SMTP_SENDER
        password = Config.SMTP_PASSWORD
        smtp_host = Config.SMTP_HOST
        smtp_port = Config.SMTP_PORT
        
        if not sender or not password:
            error_msg = "SMTP credentials not configured. Please set SMTP_SENDER and SMTP_PASSWORD in environment variables."
            app_logger.error(error_msg)
            return False, error_msg
        
        try:
            # Create message
            msg = MIMEMultipart('alternative')
            msg['Subject'] = f"🧬 Your Gene Sequence Results - {successful}/{gene_count} genes"
            msg['From'] = f"Gene Extractor <{sender}>"
            msg['To'] = to_email
            
            # Create HTML and plain text versions
            html_content = EmailService.create_results_email_html(username, gene_count, successful, organism)
            text_content = f"""
Gene Sequence Results Ready

Hi {username},

Your gene sequence extraction has been completed successfully!

Summary:
- Total Genes: {gene_count}
- Successful: {successful}
- Organism: {organism}

Attachments included:
- ZIP file with all sequences
- Metadata CSV with composition analysis  
- Metadata Excel workbook

Generated by Gene Extractor on {datetime.now().strftime('%B %d, %Y at %I:%M %p')}
            """
            
            # Attach both versions
            msg.attach(MIMEText(text_content, 'plain'))
            msg.attach(MIMEText(html_content, 'html'))
            
            # Attach ZIP file
            zip_part = MIMEBase('application', 'zip')
            zip_part.set_payload(zip_bytes)
            encoders.encode_base64(zip_part)
            zip_part.add_header('Content-Disposition', 'attachment', filename='RefSeq_sequences.zip')
            msg.attach(zip_part)
            
            # Attach CSV if provided
            if csv_bytes:
                csv_part = MIMEBase('text', 'csv')
                csv_part.set_payload(csv_bytes)
                encoders.encode_base64(csv_part)
                csv_part.add_header('Content-Disposition', 'attachment', filename='metadata.csv')
                msg.attach(csv_part)
            
            # Attach Excel if provided
            if xlsx_bytes:
                xlsx_part = MIMEBase('application', 'vnd.openxmlformats-officedocument.spreadsheetml.sheet')
                xlsx_part.set_payload(xlsx_bytes)
                encoders.encode_base64(xlsx_part)
                xlsx_part.add_header('Content-Disposition', 'attachment', filename='metadata.xlsx')
                msg.attach(xlsx_part)
            
            # Send email
            with smtplib.SMTP_SSL(smtp_host, smtp_port) as smtp:
                smtp.login(sender, password)
                smtp.send_message(msg)
            
            app_logger.info(f"Results email sent successfully to {to_email}")
            return True, "Email sent successfully!"
            
        except Exception as e:
            error_msg = f"Failed to send email: {str(e)}"
            app_logger.error(error_msg)
            return False, error_msg
